services:
  flask-app:
    image: flask-ci-cd:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s